name: Deployment

on:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - 'server/**'

permissions:
  contents: read
  packages: write
  pull-requests: write

env:
  IMAGE_NAME: dataverity
  SHA: ${{ github.event.pull_request.head.sha || github.event.after }}
  COMPARE_TAG: 0

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ env.SHA }}

      - name: Docker login
        uses: docker/login-action@b161681273e9a62136351194d2df85acea10488f
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@4b4e9c3e2d4531116a6f8ba8e71fc6e2cb6e6c8c
        with:
          driver-opts: |
            image=moby/buildkit:v0.10.6

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@c4ee3adeed93b1fa6a762f209fb01608c1a22f1e
        with:
          images: ${{ secrets.DOCKER_USER }}/${{ env.IMAGE_NAME }}
          labels: |
            org.opencontainers.image.revision=${{ env.SHA }}
          tags: |
            type=edge,branch=$repo.default_branch
            type=semver,pattern=v{{version}}
            type=sha,prefix=,suffix=,format=short

      - name: Build image and push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Docker Scout
        id: docker-scout
        uses: docker/scout-action@0133ff88fe16d4a412dc4827a8fccbccb6b583e0
        with:
          command: compare
          image: ${{ steps.meta.outputs.tags }}
          to: ${{ secrets.DOCKER_USER }}/${{ env.IMAGE_NAME }}:${{ env.COMPARE_TAG }}
          ignore-unchanged: true
          only-severities: critical,high
          write-comment: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
