name: server

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'
  pull_request:
    branches: ['*']
    paths:
      - 'server/**'

jobs:
  server-testing:
    runs-on: ubuntu-22.04

    services:
      postgres:
        image: postgres:15-alpine3.20
        env:
          POSTGRES_USER: 'dataverity-test'
          POSTGRES_PASSWORD: '1cf4eb8f04a84637'
          POSTGRES_DB: 'dataverity-test-db'
        ports:
          - 5432:5432
        options: >- 
          --health-cmd pg_isready 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install packages
        run: pip install --no-cache-dir -r requirements.dev.txt
        working-directory: ./server
      
      - name: Tests E2E
        run: coverage run pytest tests/
        working-directory: ./server
        env:
          DATABASE_URL: 'postgresql://dataverity:1cf4eb8f04a84637@localhost:5432/dataverity-test-db'
          
      - name: Coverage
        run: coveralls --repo-token=${{ secrets.COVERALLS_REPO_TOKEN }} --service=github
        working-directory: ./server

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
